// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAkUK6Ga9H9s8OVLPBtKpuy7GHHcJXGdw',
    appId: '1:954307029831:web:0598524b36c8b0ee6fba62',
    messagingSenderId: '954307029831',
    projectId: 'store-application-57679',
    authDomain: 'store-application-57679.firebaseapp.com',
    storageBucket: 'store-application-57679.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyEvqbFWHcFPsZUjRtZ8FOFzlvseioRo',
    appId: '1:954307029831:android:cfd8276777be1de76fba62',
    messagingSenderId: '954307029831',
    projectId: 'store-application-57679',
    storageBucket: 'store-application-57679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0mjVLP2UD2RX1DtMShbl6z2OpH5v_3s',
    appId: '1:954307029831:ios:7644bfedcdf0ed666fba62',
    messagingSenderId: '954307029831',
    projectId: 'store-application-57679',
    storageBucket: 'store-application-57679.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0mjVLP2UD2RX1DtMShbl6z2OpH5v_3s',
    appId: '1:954307029831:ios:8185bbb03fa2780a6fba62',
    messagingSenderId: '954307029831',
    projectId: 'store-application-57679',
    storageBucket: 'store-application-57679.firebasestorage.app',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
